@extends('layouts.tosoapp')

@section('title','特定商取引法に基づく表示')

@section('content')

<div class="table-responsive">
    <table class="table table-bordered table-sm">
        <tbody>
            <tr>
                <td>
                    業者名
                </td>
                <td>
                    とそブックス
                </td>
            </tr>
            <tr>
                <td>
                    古物商許可
                </td>
                <td>
                    第961020041420号/鹿児島県公安委員会
                </td>
            </tr>
            <tr>
                <td>
                    代表責任者
                </td>
                <td>
                    貴島大悟
                </td>
            </tr>
            <tr>
                <td>
                    営業所所在地
                </td>
                <td>
                    鹿児島県唐湊4-14-26塩満アパート102
                </td>
            </tr>
            <tr>
                <td>
                    メールアドレス
                </td>
                <td>
                    {{'toso@xn--d9jva.com'}}
                </td>
            </tr>
            <tr>
                <td>
                    URL
                </td>
                <td>
                    https://とそ.com(xn--d9jva.com)
                </td>
            </tr>
            <tr>
                <td>
                    入金方法
                </td>
                <td>
                    銀行振込、Amazonギフト券メール送信
                </td>
            </tr>
            <tr>
                <td>
                    返送
                </td>
                <td>
                    承諾確認前に返送可。
                </td>
            </tr>
        </tbody>
    </table>
</div>
@endsection